apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jemjjk-site-tls
spec:
  secretName: jemjjk-site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    commonName: jemjjk.site
  dnsNames:
    - jemjjk.site
    - www.jemjjk.site
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jemjjk.site
          - www.jemjjk.site